const mongoose = require('mongoose');
const {Schema} = mongoose;

const schema = new Schema({
    pendaftaran: {
        type: Schema.Types.ObjectId,
        required: true,
        ref: 'Pendaftaran',
    },
    
    // Pengkajian
    waktu: Date,
    auto: String,
    alloo: String,
    riwayatPenyakit: String,
    alergiObat: String,
    alergiMakanan: String,
    pantangan: String,
    keadaanUmum: String,
    kesadaran: String,
    eye: String,
    movement: String,
    verbal: String,
    td: String,
    nadi: String,
    bb: String,
    sat: String,
    suhu: String,
    rr: String,
    reguler: String,
    ews: String,
    skrinningNyeri: String,
    timbulNyeri: String,
    pencetusNyeri: String,
    upayaNyeri: String,
    gambaranNyeri: String,
    gambaranNyeriLain: String,
    penyebaranNyeri: String,
    menyebarKe: String,
    skalaNyeri: String,
    nyeriNips: String,
    nyeriBps: String,
    nyeriNrs: String,
    nyeriWongBaker: String,
    nyeriFlacc: String,
    polaNafas: String,
    kepala: String,
    kepalaLain: String,
    refleksiCahaya: String,
    pupil: String,
    isokor: String,
    sekret: String,
    anisokor: String,
    konjungtiva: String,
    sklera: String,
    hidung: String,
    mulut: String,
    faring: String,
    tonsis: String,
    telinga: String,
    telingaSekret: String,
    leher: String,
    venaJugularis: String,
    gerakanDada: String,
    inspeksiDada: String,
    retraksiDada: String,
    auskultasiDada: String,
    ictusCordis: String,
    palpasiDada: String,
    fremitusTaktil: String,
    heparLien: String,
    batasJantung: String,
    cor: String,
    pulmo: String,
    akral: String,
    crt: String,
    kuatNadi: String,
    edema: String,

    // Ringkasan
    rKeadaanUmum: String,
    rKeadaan: String,
    rEye: String,
    rMovement: String,
    rVerbal: String,
    rTd: String,
    rNadi: String,
    rBb: String,
    rSat: String,
    rSuhu: String,
    rNafas: String,
    rReguler: String,
    rEws: String,
    rNyeri: String,
    rSkalaNyeri: String,

    // Tindak lanjut
    waktuKeluar: Date,
    tindakLanjut: String,
    pindah: String,
    dirujukKe: String,
    alasanRujuk: String,
    rujukKe: String,
    rujukKeLain: String,
    pulang: String,
    menolakRawat: String,
    kontrol: String,
    edukasi: String,
    diet: String,
    minumObat: String,
    edukasiLain: String,
    obatPulang: String,

    // Masalah
    diagnosaBanding: String,
    permasalahan: String,
    targetTerukur: String,
    icd10: String,
    terapiTindakan: String,
    terapiMedika: String,
    rencanaOperasi: String,
    rencanaKonsultasi: String,
});

const Pengkajian = mongoose.model('Pengkajian', schema, 'pengkajian');

module.exports = Pengkajian;
